package org.cytoscape.massql.io;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import org.cytoscape.massql.spectra.SpectrumTable;
import org.cytoscape.massql.testsupport.Fixtures;
import org.junit.jupiter.api.Test;

/**
 * The real-world mzXML: schema 2.0, nested scans, 916 spectra.
 *
 * <p>{@code small.mzXML} was generated by our own converter, so on its own it proves only that we can
 * read what we wrote. This fixture came off an instrument via a third party and is the one that exercises
 * schema 2.0's nesting, its {@code peaksCount="3"} near-empty scans, and its scale.
 */
class MzxmlSchema20IT {

    @Test
    void theEwingFileParsesCompletely() {
        Path mzxml = Fixtures.require("data/DP00570_F02.mzxml");

        int scans = 0, ms1 = 0, ms2 = 0;
        long peaks = 0;
        int previousId = 0;
        try (SpectraStream s = SpectraFile.open(mzxml)) {
            while (s.hasNext()) {
                ScanView v = s.next();
                scans++;
                if (v.msLevel() == 1) ms1++;
                else ms2++;

                // Document order must be strictly increasing here; the nested layout must not cause
                // a
                // scan to be revisited or emitted out of order.
                assertTrue(
                        v.scanId() > previousId,
                        "scan "
                                + v.scanId()
                                + " came after "
                                + previousId
                                + " -- the nested walk is "
                                + "emitting scans out of document order");
                previousId = v.scanId();

                SpectrumTable t = v.materialize();
                assertEquals(
                        v.peakCount(),
                        t.rowCount(),
                        "scan "
                                + v.scanId()
                                + ": peaksCount disagrees with the decoded array length");
                peaks += t.rowCount();
            }
        }

        assertEquals(916, scans, "total scans");
        assertEquals(229, ms1, "MS1 scans");
        assertEquals(687, ms2, "MS2 scans");
        assertEquals(916, ms1 + ms2);
        assertTrue(peaks > 100_000, "expected six figures of peaks, got " + peaks);
    }

    @Test
    void theFileReallyIsNestedSchemaTwoPointZero() {
        // Guards the premise. If this fixture were ever replaced by a flat file, the nested code
        // path
        // would stop being exercised by any real input and only micro_nested.mzXML would cover it.
        Path mzxml = Fixtures.require("data/DP00570_F02.mzxml");
        String raw;
        try {
            raw = Files.readString(mzxml, StandardCharsets.ISO_8859_1);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        assertTrue(raw.contains("mzXML_2.0"), "expected a schema 2.0 declaration");

        // Maximum <scan> nesting depth must be 2: MS2 inside its parent MS1.
        int depth = 0, max = 0;
        for (int i = 0; i < raw.length() - 6; i++) {
            if (raw.startsWith("</scan>", i)) depth--;
            else if (raw.startsWith("<scan ", i)) {
                depth++;
                max = Math.max(max, depth);
            }
        }
        assertEquals(
                2,
                max,
                "DP00570_F02.mzxml is expected to NEST MS2 inside its parent MS1; a flat file here "
                        + "would leave the nested walk untested by any real input");
    }

    @Test
    void theElevenNearEmptyScansAreReadNotSkipped() {
        // the fixtures recorded peaksCount="3" scans as worth hand-checking. There are 11 of them
        // (the
        // spec
        // implies fewer). A three-peak scan is where an off-by-one in the interleaved
        // de-interleaving
        // shows up most starkly, and where a reader that treated tiny scans as empty would differ.
        Path mzxml = Fixtures.require("data/DP00570_F02.mzxml");
        int threePeak = 0;
        try (SpectraStream s = SpectraFile.open(mzxml)) {
            while (s.hasNext()) {
                ScanView v = s.next();
                if (v.peakCount() != 3) continue;
                threePeak++;
                SpectrumTable t = v.materialize();
                assertEquals(3, t.rowCount());
                for (int i = 0; i < 3; i++) {
                    assertTrue(t.mz(i) > 0.0, "m/z must be positive");
                    assertTrue(t.intensity(i) >= 0.0, "intensity must be non-negative");
                }
                // Sorted ascending by m/z, which the mz-window binary search depends on.
                assertTrue(t.mz(0) <= t.mz(1) && t.mz(1) <= t.mz(2), "peaks must be m/z-ascending");
            }
        }
        assertEquals(11, threePeak, "expected 11 scans with peaksCount=\"3\"");
    }

    @Test
    void nothingIsReportedAsSkipped() {
        // This file has no ms level > 2, no empty msLevel and no peaks-less scan, so a clean read
        // must
        // produce NO diagnostics. If any appear, the walk is discarding scans it should not.
        Path mzxml = Fixtures.require("data/DP00570_F02.mzxml");
        try (SpectraStream s = SpectraFile.open(mzxml)) {
            while (s.hasNext()) {
                s.next(); /* drain */
            }
            assertEquals(
                    java.util.List.of(),
                    s.diagnostics(),
                    "unexpected diagnostics on a clean file: " + s.diagnostics());
        }
    }
}
